# Generated by Django 5.1.3 on 2024-11-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyunapp', '0002_boardaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=50)),
                ('rdate', models.DateTimeField()),
                ('udate', models.DateTimeField()),
            ],
        ),
    ]
